title: "Income Classification"
author: "Harshal Patil"
logo: ""
execute:
  execute_notebooks: "off"

myst_enable_extensions:
  - linkify
  - jupyter

html:
  output_folder: docs
  baseurl: /Mood_classification_book/
  use_repository_button: true

repository:
  url: https://github.com/Pofit188/Income_notebook
  path_to_book: ./
  branch: main



